### ISSUE TITLE
Xcode 7GM + OSX 10.11

### ISSUE THREAD

**Issue by liucoj** [cxa/UIMenuItem-CXAImageSupport#6]
Hi @cxa , 
compiling under Xcode 7 GM on MacOSX 10.11 GM didn't work, 
it results in:
errors > "no visible @ interface for 'CIImage' declares the selector 'size'" on lines 217, 229
warnings > Incompatible pointer types initializing 'UIImage *' with an expression of type 'CIImage * _Nullable"

any help?

**Comment by cxa** [comment]
Fixed.

**Comment by liucoj** [comment]
thank you!!
